networks:
  public:
    external: true

volumes:
  data:

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: pocket-id
    restart: unless-stopped
    networks:
      - public
    ports:
      - 127.0.0.1:1411:1411
    volumes:
      - data:/app/data
    environment:
      - TZ=Asia/Kolkata
      - PGID=1000
      - PUID=1000
      - TRUST_PROXY=true
      - LOG_LEVEL=warn
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - APP_URL=${APP_URL}
    healthcheck:
      test: ["CMD", "/app/pocket-id", "healthcheck"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 32M

  backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/backup/pocket-id:ro
      - ${LOCAL_BACKUP_DESTINATION}:/archive
    environment:
      - TZ=Asia/Kolkata
      - BACKUP_CRON_EXPRESSION=0 30 23 * * 1
      - BACKUP_RETENTION_DAYS=365
      - BACKUP_FILENAME=pocket-id-%Y-%m-%dT%H-%M-%S.tar.gz
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
    depends_on:
      pocket-id:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 32M

