networks:
  public:
    external: true

services:
  docktail:
    image: ghcr.io/marvinvr/docktail:1.6
    container_name: docktail
    restart: unless-stopped
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale:/var/run/tailscale
    environment:
      - LOG_LEVEL=warn
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "tailscale", "serve", "status", "--json"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 32M

