networks:
  public:
    external: true

volumes:
  data:

services:
  vault:
    image: ghcr.io/dani-garcia/vaultwarden:1.37.1-alpine
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - public
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - data:/data
    environment:
      - TZ=Asia/Kolkata
      - DOMAIN=${DOMAIN}
      - LOG_LEVEL=info
      - SHOW_PASSWORD_HINT=false
      - SSO_ENABLED=true
      - SSO_ONLY=false
      - SSO_SIGNUPS_MATCH_EMAIL=true
      - SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION=true
      - SSO_SCOPES=email profile groups offline_access
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
      - SSO_AUTHORITY=${SSO_AUTHORITY}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:80/alive"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 32M

  local-backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/backup/vaultwarden:ro
      - ${LOCAL_BACKUP_DESTINATION}:/archive
    environment:
      - TZ=Asia/Kolkata
      - BACKUP_CRON_EXPRESSION=0 0 3 * * *
      - BACKUP_RETENTION_DAYS=15
    depends_on:
      vault:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 32M

  r2-backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/backup/vaultwarden:ro
    environment:
      - TZ=Asia/Kolkata
      - BACKUP_CRON_EXPRESSION=0 0 3 * * 0
      - BACKUP_RETENTION_DAYS=182
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
    depends_on:
      vault:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 32M

